### PR TITLE
fix: Typo in Document and Signer + add the function downloadFinalDocument()

### PR DESCRIPTION
**Pull request by Snowbaha**
To avoid issue with some IDE / Framework, I fixed the Typo of Document and Signer with Getter.

I added the possibility  to stream the result of PDF document or to get the direct URL.

I added the condition with a "[stream](https://docs.guzzlephp.org/en/stable/request-options.html#stream)" payload. I think if we keep this logic, we have to refactor `startRequest()`
The idea is there, you can change if needed :)

### CODE REVIEW

**Comment by Snowbaha** [comment]
Hello, any news from it?

**Comment by milanlatinovic** [comment]
Hi @Snowbaha,

Thanks for providing your fix and ideas here, much appreciated.
If I understand correctly you have two things here 1) typo fix and 2) proposal on how to extend a feature.

Can you please create two issues for these items, quickly describe them and then make two pull requests linking to these issues? I will review it then, for now I will close this pull request.

The reason for asking:
- Since this is community sdk we need to have issues for any code changes (even typo fixes) so we can keep track of what was happening and also make a new releases properly.
- In general, we are trying not to mix bug fixes and feature extensions in same pull requests. They can and will be in the same release, but they should come as a separated pull requests which are basing on existing issues.

You can use this template to create new issues
https://github.com/eversign/eversign-php-sdk/issues/new/choose

Thanks,
Milan

**Comment by Snowbaha** [comment]
Hello, I would like but when I commited, it updated the original one. I don't know how to do with 2 separates PR :(

**Comment by milanlatinovic** [comment]
Well, you need to create two branches and create one PR per branch, you can not do everything in a same branch.

Just a reminder, it is not only about separated PRs, you should make issues first and link your PRs to those issues.

Keep in mind that this is public SDK which is used by many people, we have to be careful about what we commit and to keep a good track of the reasons behind it.

**Pull request closed without merging**
