### PR TITLE
Fix initialisation of CheckBox field

### PR DESCRIPTION
**Pull request by linux019**
For https://github.com/eversign/eversign-php-sdk/issues/14

### CODE REVIEW

**Comment by dominikkukacka** [comment]
As discussed in #14 wouldn't a protected variable make more sense?

**Comment by linux019** [comment]
I would like to do not change whole FormField class, because it's need to make all properties as protected

**Comment by dominikkukacka** [comment]
I don't think this would be a problem right?

**Comment by dominikkukacka** [comment]
Thanks!

**Pull request merged**
