### PR TITLE
Add required to CheckboxField and RadioField

### PR DESCRIPTION
**Pull request by clemcoder**
Make CheckboxField and RadioField mandatory.

### CODE REVIEW

**Comment by milanlatinovic** [comment]
Hi, thanks for proposing contributions to our SDK. However, commit message is not linked to any open issues and does not clarifies on why increased restrictions are needed. You can use your code locally if it works for you, but to add it to repository we need to have clear explanation of value that it adds to all SDK users. Thanks!

**Comment by clemcoder** [comment]
Hi, here is the explanation :

In the actual sdk, all CheckboxField and RadioField are optional.
I needed to add mandatory CheckboxField and RadioField in my documents.
This commit add the possibility to use the "required" attribute (described in the Eversign documentation [https://eversign.com/api/documentation/fields#field-types](https://eversign.com/api/documentation/fields#field-types)) with CheckboxField and RadioField.

For CheckboxField, this attribute force the signer to check the field to complete the signature.
For RadioField, this attribute force the signer to check one or more fields in the radio button groups to complete the signature.

Hope this fits !

**Comment by milanlatinovic** [comment]
Hi @clemcoder 

Thanks for clarifying this one, yes Requireable trait that you included is matching with API specs https://eversign.com/api/documentation/fields#field-types and use case makes sense. I reopened merge request and I will approve and merge it.

Thanks!

**Review by milanlatinovic — APPROVED** [review]

**Comment by clemcoder** [comment]
Great thanks !

**Pull request merged**
